activation_function: gelu_new
gamma: 0.075
lr: 0.001
lr_final: 0.0001
max_epochs: 200
max_num_particles: 150
n_embd: 256
n_head: 4
n_layer: 4
num_jets: 200000
num_timesteps: 100
time_eps: 1.0e-05
vocab_size: 9
