config: !!python/object:argparse.Namespace
  activation: gelu_new
  batch_size: 256
  comet_api_key: 8ONjCXJ1ogsqG1UxQzKxYn7tz
  comet_workspace: dfaroughy
  dir: /home/df630/Multimodal-flows
  dropout_att: 0.1
  dropout_emb: 0.1
  dropout_res: 0.1
  experiment_id: null
  lr: 0.001
  lr_final: 0.0001
  max_epochs: 250
  max_seq_length: 150
  n_embd: 64
  n_head: 4
  n_inner: 256
  n_layer: 4
  num_jets: 100000
  num_nodes: 1
  project: jet_sequences
  tags: null
  temperature: 1.0
  top_k: null
  train_frac: 0.8
  vocab_size: 8
